CREATE DATABASE vitae WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

CREATE USER vitae WITH PASSWORD 'pgpassword';
GRANT ALL PRIVILEGES ON DATABASE vitae TO vitae;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vitae;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vitae;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO vitae;
ALTER DATABASE vitae OWNER TO vitae;
ALTER ROLE vitae SET statement_timeout TO '5s';

select 1
